on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install AWS Lightsail
        run: curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"

      - name: Make Lightsail Plugin Executable
        run: sudo chmod +x /usr/local/bin/lightsailctl

      - name: Install MongoDB Server
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 4B7C549A058F8B6B
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          sudo systemctl enable mongod

      - name: Verify MongoDB Installation
        run: |
          mongod --version
          mongo --version

      - name: Build the Image
        run: docker build -t blog-container -f Dockerfile .

      - name: Login to AWS and push to Lightsail
        run: aws lightsail push-container-image --region us-east-1 --service-name container-service-1 --label blog-container2 --image blog-container:latest
